# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [34]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import gmaps.datasets
import os
import gmaps
import gmaps.datasets
import ipywidgets as widgets
import geopy

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [35]:
# Load csv file created in Part I
city_data_csv = "../WeatherPy/output_data/city.csv"

In [36]:
# Create dataframe
city_df = pd.read_csv(city_data_csv)
city_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,castro,-24.7911,-50.0119,61.00,59.0,79.0,6.67,BR,1.660646e+09
1,jamestown,42.0970,-79.2353,61.02,74.0,100.0,4.00,US,1.660646e+09
2,barrow,71.2906,-156.7887,32.86,98.0,100.0,14.14,US,1.660645e+09
3,busselton,-33.6500,115.3333,55.09,75.0,45.0,17.83,AU,1.660646e+09
4,carnarvon,-24.8667,113.6333,62.67,94.0,75.0,5.75,AU,1.660646e+09
...,...,...,...,...,...,...,...,...,...
616,kaeo,-35.1000,173.7833,62.33,95.0,100.0,19.24,NZ,1.660646e+09
617,talaya,61.3833,152.7500,47.97,94.0,100.0,4.94,RU,1.660646e+09
618,grimari,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
619,laguna,38.4210,-121.4238,76.17,62.0,0.0,3.44,US,1.660646e+09
620,garowe,8.4054,48.4845,92.71,31.0,17.0,24.45,SO,1.660646e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [37]:
# Configure gmaps with API key
gmaps.configure(api_key = g_key)

In [38]:
#Convert Humidity to float and store
# HINT: be sure to handle NaN values
city_df = city_data_df.dropna()

# Store 'Lat' and 'Lng' into  locations 
locations = city_df[["Lat", "Lng"]]
humidity = city_df["Humidity"]

# Creating a Humidity heatmap layer
fig = gmaps.figure(center = [0,0] ,zoom_level = 3)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                 dissipating=False, 
                                 max_intensity=100, 
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [39]:
# Narrow down the DataFrame to find your ideal weather condition.
weather_df = city_data_df.loc[(city_data_df["Max Temp"] < 80) 
                                    & (city_data_df["Max Temp"] > 70) 
                                    & (city_data_df["Wind Speed"] < 10) 
                                    & (city_data_df["Cloudiness"] == 0),:].dropna()
weather_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
17,rodrigues alves,-7.7380,-72.6509,70.48,92.0,0.0,2.66,BR,1.660646e+09
75,saint george,37.1041,-113.5841,77.59,67.0,0.0,0.00,US,1.660646e+09
152,cognac,45.5000,-0.2500,75.65,60.0,0.0,4.61,FR,1.660646e+09
162,lake charles,30.2131,-93.2044,79.99,94.0,0.0,0.00,US,1.660646e+09
177,bogalusa,30.7910,-89.8487,78.75,88.0,0.0,0.00,US,1.660646e+09
201,ahuimanu,21.4447,-157.8378,76.86,82.0,0.0,3.44,US,1.660646e+09
238,port elizabeth,-33.9180,25.5701,75.09,31.0,0.0,7.00,ZA,1.660645e+09
260,makakilo city,21.3469,-158.0858,75.69,73.0,0.0,0.00,US,1.660646e+09
281,cayenne,4.9333,-52.3333,77.09,1.0,0.0,0.00,GF,1.660646e+09
350,tucuma,-0.1833,-50.0500,75.36,89.0,0.0,4.63,BR,1.660646e+09
357,progreso,21.2833,-89.6667,75.31,91.0,0.0,6.93,MX,1.660646e+09
371,lasa,46.6166,10.7002,74.28,52.0,0.0,3.76,IT,1.660646e+09
376,houma,29.5958,-90.7195,78.80,93.0,0.0,0.00,US,1.660646e+09
455,inhambane,-23.8650,35.3833,74.37,43.0,0.0,7.47,MZ,1.660646e+09
460,belle glade,26.6845,-80.6676,78.06,89.0,0.0,5.68,US,1.660646e+09
619,laguna,38.4210,-121.4238,76.17,62.0,0.0,3.44,US,1.660646e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [40]:
hotel_df = ideal_weather_df[["City", "Country", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

                City Country      Lat       Lng Hotel Name
17   rodrigues alves      BR  -7.7380  -72.6509
75      saint george      US  37.1041 -113.5841
152           cognac      FR  45.5000   -0.2500
162     lake charles      US  30.2131  -93.2044
177         bogalusa      US  30.7910  -89.8487
201         ahuimanu      US  21.4447 -157.8378
238   port elizabeth      ZA -33.9180   25.5701
260    makakilo city      US  21.3469 -158.0858
281          cayenne      GF   4.9333  -52.3333
350           tucuma      BR  -0.1833  -50.0500
357         progreso      MX  21.2833  -89.6667
371             lasa      IT  46.6166   10.7002
376            houma      US  29.5958  -90.7195
455        inhambane      MZ -23.8650   35.3833
460      belle glade      US  26.6845  -80.6676
619           laguna      US  38.4210 -121.4238

In [41]:
# Set parameters to serach for a hotel
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Iterate through cities
for index, row in hotel_df.iterrows():
    # get lat, lng from dataframe
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while keeping original params in place
    params["location"] = f"{lat},{lng}"
    
    # Create base url to search nearby hotel     
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Make request
    print(f"Retrieving results for city: {row['City']}")
    hotel_name = requests.get(base_url, params=params).json()
    
    # extract results
    hotel_name = hotel_name['results']
    
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_name[0]['name']
        print(f"Closest hotel is {hotel_name[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = hotel_name[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving results for city: rodrigues alves
Closest hotel is Pousada Aconchego.
------------
Retrieving results for city: saint george
Closest hotel is Best Western Plus Abbey Inn.
------------
Retrieving results for city: cognac
Closest hotel is Domaine de Pladuc.
------------
Retrieving results for city: lake charles
Closest hotel is La Quinta Inn & Suites by Wyndham Lake Charles Casino Area.
------------
Retrieving results for city: bogalusa
Closest hotel is Traveler's Rest Motel.
------------
Retrieving results for city: ahuimanu
Closest hotel is Paradise Bay Resort.
------------
Retrieving results for city: port elizabeth
Closest hotel is 39 On Nile Guest House.
------------
Retrieving results for city: makakilo city
Closest hotel is Marriott's Ko Olina Beach Club.
------------
Retrieving results for city: cayenne
Closest hotel is HÃ´tel Le Dronmi.
------------
Retrieving results for city: tucuma
Missing field/result... skipping.
------------
Retrieving results for city: progreso
Closest hotel is Playa Linda Hotel.
------------
Retrieving results for city: lasa
Closest hotel is Pension FeldgÃ¤rtenhof.
------------
Retrieving results for city: houma
Closest hotel is Courtyard by Marriott Houma.
------------
Retrieving results for city: inhambane
Closest hotel is Oceano.
------------
Retrieving results for city: belle glade
Closest hotel is Mid-City Trailer Park.
------------
Retrieving results for city: laguna
Closest hotel is Holiday Inn Express & Suites Elk Grove Central - Hwy 99, an IHG Hotel.
------------

In [42]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [43]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)